services:
  # backend
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env.development
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/usr/src/app/src
      # - /usr/src/app/node_modules
    depends_on:
      database:
        condition: service_healthy

  # database
  database:
    image: postgres
    container_name: database
    env_file:
      - ./backend/.env.development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # frontend
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ./frontend/.env.development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
    depends_on:
      - backend
volumes:
  pgdata:
